language: node_js

node_js:"6.10.3"

sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    
before_script: 
  - "npm install -g @angular/cli"
  
script:
  - ng build --prod  
