language: node_js
node_js:"6.10.3"
branches:
  only:
    - master
before_script: 
  - npm install -g @angular/cli
script:
  - ng build --prod  
deploy:
  provider: cloudfoundry
  edge: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
