language: node_js
node_js:
  - "6.10.3"

branches:
  only:
    - master

before_script: 
   "npm uninstall --save-dev angular-cli"
   "npm cache clear"
   "npm install --save-dev @angular/cli@latest"  
script:
   "ng build --prod"
   "bash ./.build.sh"
  
before_deploy:
  "cd dist"
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master